### ISSUE TITLE
Update information for November 2024

### ISSUE THREAD

**Issue by D4LMwastaken** [LHSCoding/LHSCC-Original-Website-Archived-#13]
### Hi everyone!
We need to update information on the website to be correct for November 2024.

**Comment by S-Orbital** [comment]
Uhhhhhhhhhh ok, I'll restructure the website

**Comment by D4LMwastaken** [comment]
Ok, creating an issue and assigning that to you...

**Comment by D4LMwastaken** [comment]
Finished, removing this issue as it is not November 2024 anymore, it is December 2024.
